import = ["~/.config/alacritty/themes/themes/night_owl.toml"]
live_config_reload = true

[font]
size = 16.0

[font.normal]
family = "CaskaydiaCove Nerd Font"
style = "Regular"

[window]
decorations = "Buttonless"
startup_mode = "Maximized"
dynamic_padding = false

[window.padding]
x =10
y = 8

[mouse]
hide_when_typing = true
